### ISSUE TITLE
What make the acc from 90.55 to 92.0?

### ISSUE THREAD

**Issue by elk-april** [JiaweiShiCV/Amend-Representation-Module#12]
HI, I notice that you modified the acc of RAFDB and it obtain a great improvement.
Could you tell me the modify?

**Comment by JiaweiShiCV** [comment]
The batch size has been changed from 256 to 64. That makes a difference.

**Comment by elk-april** [comment]
谢谢回复！

**Comment by elk-april** [comment]
你好，请问是否可以开源 affectnet数据集的数据加载代码？
或者，我考虑复现这一部分代码：
我是否可以认为你的采样方式是：按照过采样的方式对每个类别设置概率，再加上每个epoch限制单个类别的采样上限，从而达到每个epoch内的data balance？

**Comment by JiaweiShiCV** [comment]
@elk-april 均衡采样的方式是你所说的那样。并且AffectNet的网络参数与RAF-DB不同，需要调整。我目前离校实习，设备和代码是学弟在玩，是否开源得遵从导师意见。

**Comment by elk-april** [comment]
好的蛤，原来是网络参数也有修改，难怪我没法复现来着。
这是一篇很好的工作，RAFDB上的效果特别明显。

**Comment by elk-april** [comment]
你好，我在尝试修改ARM的模型参数，但是效果不佳，无法复现论文中的65.20。
是否能告知针对affectnet，模型的修改在哪里吗。

**Comment by JiaweiShiCV** [comment]
你好，你可以从两个方向进行改进：
1、de-albino的卷积核大小和步长，以及该卷积层的个数 
2、leaning rate schedule

**Comment by elk-april** [comment]
谢谢你的回复，我会尝试做几组对照试验的；
ps.目前我使用rafdb模型可以到达64.3。

**Comment by elk-april** [comment]
很遗憾，搜索了一个周末的卷积尺寸+step还是没有得到更好的效果。0. 0

**Comment by elk-april** [comment]
另外，可以达到相似的精度，大概有

**Comment by cezheng06** [comment]
> 你好，请问是否可以开源 affectnet数据集的数据加载代码？
> 或者，我考虑复现这一部分代码：
> 我是否可以认为你的采样方式是：按照过采样的方式对每个类别设置概率，再加上每个epoch限制单个类别的采样上限，从而达到每个epoch内的data balance？

您好 可以分享一下AffectNet的数据加载代码吗？ 万分感谢。我的邮箱：czheng6@uncc.edu

**Comment by elk-april** [comment]
你好，我在复现论文的重采样策略后，发现效果不是特别好。建议还是用这个：
https://github.com/kaidic/LDAM-DRW
我是用这里的 resample







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月5日(星期四) 晚上7:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [JiaweiShiCV/Amend-Representation-Module] What make the acc from 90.55 to 92.0? (#12)





  
你好，请问是否可以开源 affectnet数据集的数据加载代码？
 或者，我考虑复现这一部分代码：
 我是否可以认为你的采样方式是：按照过采样的方式对每个类别设置概率，再加上每个epoch限制单个类别的采样上限，从而达到每个epoch内的data balance？
  
您好 可以分享一下AffectNet的数据加载代码吗？ ***@***.***
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cezheng06** [comment]
> 你好，我在复现论文的重采样策略后，发现效果不是特别好。建议还是用这个： https://github.com/kaidic/LDAM-DRW 我是用这里的 resample
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年8月5日(星期四) 晚上7:07 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [JiaweiShiCV/Amend-Representation-Module] What make the acc from 90.55 to 92.0? (#12) 你好，请问是否可以开源 affectnet数据集的数据加载代码？ 或者，我考虑复现这一部分代码： 我是否可以认为你的采样方式是：按照过采样的方式对每个类别设置概率，再加上每个epoch限制单个类别的采样上限，从而达到每个epoch内的data balance？ 您好 可以分享一下AffectNet的数据加载代码吗？ ***@***.*** — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你是用的4G的AffectNet（March 2021 released）吗？ 我主要是不太会写新的这个dataloader 采样这块我能稍后再写
