### ISSUE TITLE
About the ablation for De-albino module

### ISSUE THREAD

**Issue by myt889** [JiaweiShiCV/Amend-Representation-Module#13]
Hi, Jiawei Shi
     Thank your for your amazing work and share the code, I just try to reproduce the result report in the paper. I wond konw that if I just only use the  De-albino module after the ResNet18 backbone, but the result of best val_acc is 86.73%, not as the same with your result with 87.32%. Since  without the anxiliary block of FA, I just adpot the reshape operation to  make the output feature map with size of 512*7*7 to fit for the input size of the  De-albino module, am I right? Looking forward to your reply,thank you very much.

**Comment by JiaweiShiCV** [comment]
What is the shape of the input feature map before applying our method?

**Comment by myt889** [comment]
The shape of the  input feature map before applying De-albino module is 512*7*7,the batch size is 64.

**Comment by myt889** [comment]
The shape of the input feature map before applying De-albino module is 512x7x7,the batch size is 64.

**Comment by JiaweiShiCV** [comment]
First of all, I am sure that it is inappropriate to use the reshape operation.
You said you reshaped the feature map to 512x7x7? What shape was it before?

**Comment by myt889** [comment]
> First of all, I am sure that it is inappropriate to use the reshape operation.
> You reshaped the origin feature map to 512x7x7. What shape was it before? De-albino block should be applied directly on the origin feature map.

I am sorry, maybe I made you confuse in last issue.
First of all, I obtain the feature map with size 512x7x7 from the resnet18 backbone(without the Avgpool layer). Then, without the pixelShuffle operation,  in order to meet the input size of the De-albino block, I reshape the 512x7x7  to 2x112x112. 

As you say, " it is inappropriate to use the reshape operation,De-albino block should be applied directly on the origin feature map.", how to make 512x7x7 feature map fit for De-albino block( taking conv2d with kernel size=32,s=8,p=0)?

**Comment by myt889** [comment]
Hi，JiaweiShiCV，
      I still have a question, how did you obtain the val_acc of 92.05% on RAF-DB? I just obtain the acc of 90.16% with trainning batch_size of 64 and testing batch_size of 64.

**Comment by JiaweiShiCV** [comment]
Conv2d(in_channels=512, out_channels=512, kernel_size=5, stride=1, padding=0)
You can try to insert the above convolution before GAP, and then you will see an improvement. Finally, removing GAP will achieve the acc in the paper.

**Comment by JiaweiShiCV** [comment]
The batch size is important for SA block. u should adjust the bs to 256 for training.



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 11, 2021 10:07 AM
To: ***@***.***&gt;;
Cc: "Jiawei ***@***.******@***.***&gt;;
Subject: Re: [JiaweiShiCV/Amend-Representation-Module] About the ablation for De-albino module (#13)




 
Hi，JiaweiShiCV，
 I still have a question, how did you obtain the val_acc of 92.05% on RAF-DB? I just obtain the acc of 90.16% with trainning batch_size of 64 and testing batch_size of 64.

**Comment by myt889** [comment]
> The batch size is important for SA block. u should adjust the bs to 256 for training.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Jul 11, 2021 10:07 AM To: ***@***.***&gt;; Cc: "Jiawei ***@***.******@***.***&gt;; Subject: Re: [JiaweiShiCV/Amend-Representation-Module] About the ablation for De-albino module (#13) Hi，JiaweiShiCV， I still have a question, how did you obtain the val_acc of 92.05% on RAF-DB? I just obtain the acc of 90.16% with trainning batch_size of 64 and testing batch_size of 64. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

ok,thank you very much.
