### ISSUE TITLE
Share Affinity

### ISSUE THREAD

**Issue by PanXiangshuai** [JiaweiShiCV/Amend-Representation-Module#2]
你好，我也不是很理解为什么要加上每个样本的平均值，这一批次的样本之间是有关联的吗？

**Comment by sunmusik** [comment]
#1 我刚刚解答了这个问题的第一位提问者，你可以参考一下。

**Comment by hewumars** [comment]
@JiaweiShiCV 
你好，你测试过用单张图片推理吗？准确率很低呀，没搞清楚怎么回事，代码好像没看出什么错误。 emo_proba 一般都小于0.4。 
```python
import numpy as np
import torch.utils.data as data
from torchvision import transforms
import cv2
import os,sys, torch
import Networks
import yaml
from tqdm import tqdm
from PIL import Image
from facial_analysis import FacialImageProcessing


f = open(sys.argv[1],'r')
args = yaml.safe_load(f.read())
f.close()
model = Networks.ResNet18_ARM___RAF()
data_transforms_val = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
if args['pretrained']:
    print("Loading pretrained weights...", args['pretrained'])
    pretrained = torch.load(args['pretrained'])
    pretrained_state_dict = pretrained
    model_state_dict = model.state_dict()
    loaded_keys = 0
    total_keys = 0
    for key in pretrained_state_dict:
        if ((key == 'fc.weight') | (key == 'fc.bias')):
            pass
        else:
            model_state_dict[key] = pretrained_state_dict[key]
            total_keys += 1
            if key in model_state_dict:
                loaded_keys += 1
    print("Loaded params num:", loaded_keys)
    print("Total params num:", total_keys)
    model.load_state_dict(model_state_dict, strict=False)
    if args['export_onnx']:
        dummy_input = torch.randn(1, 3, 224, 224).to('cuda')
        torch.onnx.export(model.to('cuda'), dummy_input, "armnet.onnx", verbose=True, opset_version=10)
RAF_DB_EMO_DICT = {
    0: "Surprise",
    1: "Fear",
    2: "Disgust",
    3: "Happiness",
    4: "Sadness",
    5: "Anger",
    6: "Neutral",
}

CK_DATA_DIR = '/workspace/share_data/FacialEmotionRecognization/CK+/'#ExpAsian'  #

imgProcessing = FacialImageProcessing(False)

model.to('cuda')
model.eval()
frame_id = 0
for class_name in tqdm(os.listdir(CK_DATA_DIR)):
    if class_name in class_to_idx:
        class_dir=os.path.join(CK_DATA_DIR,class_name)
        y=class_to_idx[class_name]
        for img_name in os.listdir(class_dir):
            filepath=os.path.join(class_dir,img_name)
            img = cv2.imread(filepath)
            h, w = img.shape[:2]

            frame_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            faces, _ = imgProcessing.detect_faces(frame_rgb)
            for i in range(0, faces.shape[0]):
                confidence = faces[i, 4]
                if confidence < 0.5:
                    continue
                box = faces[i, 0:4]
                start_x, start_y, end_x, end_y = box.astype("int")

                # covnert to square images
                center_x, center_y = (start_x + end_x) // 2, (start_y + end_y) // 2
                square_length = ((end_x - start_x) + (end_y - start_y)) // 2 // 2

                square_length *= 1.1

                start_x = max(int(center_x - square_length), 0)
                start_y = max(int(center_y - square_length), 0)
                end_x = min(int(center_x + square_length), w - 1)
                end_y = min(int(center_y + square_length), h - 1)

                cv2.rectangle(
                    img, (start_x, start_y), (end_x, end_y), (179, 255, 179), 2
                )

                face = frame_rgb[start_y:end_y, start_x:end_x]

                img_tensor = data_transforms_val(face)
                img_tensor.unsqueeze_(0)
                scores = model(img_tensor.to('cuda'))
                scores=torch.softmax(scores[0],dim=1)

                emo_proba, emo_idx = torch.max(scores, dim=1)
                emo_idx = emo_idx.item()
                emo_proba = emo_proba.item()

                emo_label = RAF_DB_EMO_DICT[emo_idx]

                label_size, base_line = cv2.getTextSize(
                    "{}: 000".format(emo_label), cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2
                )

                cv2.rectangle(
                    img,
                    (end_x, start_y + 1 - label_size[1]),
                    (end_x + label_size[0], start_y + 1 + base_line),
                    (223, 128, 255),
                    cv2.FILLED,
                )
                cv2.putText(
                    img,
                    "{} {}".format(emo_label, int(emo_proba * 100)),
                    (end_x, start_y + 1),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.8,
                    (0, 0, 0),
                    2,
                )
            cv2.imshow(imgpath[frame_id].split('/')[-2], img)
            cv2.waitKey()
            save_path = os.path.join('../data/', imgpath[frame_id].split('/')[-2])
            if not os.path.exists(save_path):
                os.mkdir(save_path)
            cv2.imwrite(save_path + f'/{emo_proba:.4f}_{emo_label}_{pre[frame_id]}.jpg', img)
            frame_id = frame_id + 1
```

**Comment by hewumars** [comment]
难怪测试一直有问题，原来是pretrained有问题。什么时候能提供pretrained weight。

**Comment by JiaweiShiCV** [comment]
> 难怪测试一直有问题，原来是pretrained有问题。什么时候能提供pretrained weight。

都怪我当时训练完后改了模块名称，其实可以想办法在加载模型时把报错的名字调整下。我最近时间有点紧，这个代码其实训练成本不高，单RTX 1080ti 可以在半个小时左右出结果，所以你也可以尝试自己训练。

**Comment by hewumars** [comment]
知道，我自己在fer2013上训练了。val acc能到70%，但是我上面这个测试代码出来的结果依然不太对。
```shell
batch_size: 256
Loading pretrained weights... ../model/checkpoints/epoch27_acc0.9078.pth
Loaded params num: 3
Total params num: 3
Train set size: 28709
Validation set size: 3589
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.0001
)
[Epoch 1] Training accuracy: 0.4450. Loss: 1.483 LR: 0.001000
[Epoch 1] Validation accuracy:0.4511. Loss:1.681
best_acc:0.4511
[Epoch 2] Training accuracy: 0.5796. Loss: 1.110 LR: 0.000900
[Epoch 2] Validation accuracy:0.2953. Loss:2.391
[Epoch 3] Training accuracy: 0.6148. Loss: 1.028 LR: 0.000810
[Epoch 3] Validation accuracy:0.5754. Loss:1.173
best_acc:0.5754
[Epoch 4] Training accuracy: 0.6374. Loss: 0.969 LR: 0.000729
[Epoch 4] Validation accuracy:0.5985. Loss:1.131
best_acc:0.5985
[Epoch 5] Training accuracy: 0.6540. Loss: 0.920 LR: 0.000656
[Epoch 5] Validation accuracy:0.6294. Loss:0.980
Model saved.
best_acc:0.6294
[Epoch 6] Training accuracy: 0.6713. Loss: 0.875 LR: 0.000590
[Epoch 6] Validation accuracy:0.6110. Loss:0.995
[Epoch 7] Training accuracy: 0.6880. Loss: 0.837 LR: 0.000531
[Epoch 7] Validation accuracy:0.6325. Loss:0.938
Model saved.
best_acc:0.6325
[Epoch 8] Training accuracy: 0.7040. Loss: 0.793 LR: 0.000478
[Epoch 8] Validation accuracy:0.6239. Loss:1.083
[Epoch 9] Training accuracy: 0.7215. Loss: 0.752 LR: 0.000430
[Epoch 9] Validation accuracy:0.6645. Loss:0.901
Model saved.
best_acc:0.6645
[Epoch 10] Training accuracy: 0.7321. Loss: 0.719 LR: 0.000387
[Epoch 10] Validation accuracy:0.6539. Loss:0.922
[Epoch 11] Training accuracy: 0.7548. Loss: 0.666 LR: 0.000349
[Epoch 11] Validation accuracy:0.6275. Loss:1.001
[Epoch 12] Training accuracy: 0.7681. Loss: 0.631 LR: 0.000314
[Epoch 12] Validation accuracy:0.6464. Loss:0.999
[Epoch 13] Training accuracy: 0.7863. Loss: 0.585 LR: 0.000282
[Epoch 13] Validation accuracy:0.6701. Loss:0.910
Model saved.
best_acc:0.6701
[Epoch 14] Training accuracy: 0.8053. Loss: 0.535 LR: 0.000254
[Epoch 14] Validation accuracy:0.6807. Loss:0.936
Model saved.
best_acc:0.6807
[Epoch 15] Training accuracy: 0.8251. Loss: 0.489 LR: 0.000229
[Epoch 15] Validation accuracy:0.6740. Loss:0.924
[Epoch 16] Training accuracy: 0.8445. Loss: 0.437 LR: 0.000206
[Epoch 16] Validation accuracy:0.6885. Loss:0.955
Model saved.
best_acc:0.6885
[Epoch 17] Training accuracy: 0.8605. Loss: 0.396 LR: 0.000185
[Epoch 17] Validation accuracy:0.6787. Loss:0.987
[Epoch 18] Training accuracy: 0.8782. Loss: 0.351 LR: 0.000167
[Epoch 18] Validation accuracy:0.6893. Loss:1.045
Model saved.
best_acc:0.6893
[Epoch 19] Training accuracy: 0.8879. Loss: 0.321 LR: 0.000150
[Epoch 19] Validation accuracy:0.6821. Loss:1.018
[Epoch 20] Training accuracy: 0.9050. Loss: 0.276 LR: 0.000135
[Epoch 20] Validation accuracy:0.6874. Loss:1.206
[Epoch 21] Training accuracy: 0.9202. Loss: 0.240 LR: 0.000122
[Epoch 21] Validation accuracy:0.6893. Loss:1.085
[Epoch 22] Training accuracy: 0.9295. Loss: 0.213 LR: 0.000109
[Epoch 22] Validation accuracy:0.6832. Loss:1.167
[Epoch 23] Training accuracy: 0.9364. Loss: 0.195 LR: 0.000098
[Epoch 23] Validation accuracy:0.6927. Loss:1.188
Model saved.
best_acc:0.6927
[Epoch 24] Training accuracy: 0.9479. Loss: 0.163 LR: 0.000089
[Epoch 24] Validation accuracy:0.6927. Loss:1.160
[Epoch 25] Training accuracy: 0.9519. Loss: 0.150 LR: 0.000080
[Epoch 25] Validation accuracy:0.6988. Loss:1.166
Model saved.
best_acc:0.6988
[Epoch 26] Training accuracy: 0.9600. Loss: 0.131 LR: 0.000072
[Epoch 26] Validation accuracy:0.6921. Loss:1.183
[Epoch 27] Training accuracy: 0.9634. Loss: 0.117 LR: 0.000065
[Epoch 27] Validation accuracy:0.6899. Loss:1.221
[Epoch 28] Training accuracy: 0.9669. Loss: 0.105 LR: 0.000058
[Epoch 28] Validation accuracy:0.6913. Loss:1.255
[Epoch 29] Training accuracy: 0.9712. Loss: 0.091 LR: 0.000052
[Epoch 29] Validation accuracy:0.6952. Loss:1.241
[Epoch 30] Training accuracy: 0.9744. Loss: 0.087 LR: 0.000047
[Epoch 30] Validation accuracy:0.6902. Loss:1.278
[Epoch 31] Training accuracy: 0.9767. Loss: 0.081 LR: 0.000042
[Epoch 31] Validation accuracy:0.6949. Loss:1.271
[Epoch 32] Training accuracy: 0.9796. Loss: 0.073 LR: 0.000038
[Epoch 32] Validation accuracy:0.6971. Loss:1.297
[Epoch 33] Training accuracy: 0.9806. Loss: 0.069 LR: 0.000034
[Epoch 33] Validation accuracy:0.6963. Loss:1.283
[Epoch 34] Training accuracy: 0.9816. Loss: 0.064 LR: 0.000031
[Epoch 34] Validation accuracy:0.6943. Loss:1.296
[Epoch 35] Training accuracy: 0.9828. Loss: 0.060 LR: 0.000028
[Epoch 35] Validation accuracy:0.7016. Loss:1.306
Model saved.
best_acc:0.7016
[Epoch 36] Training accuracy: 0.9849. Loss: 0.054 LR: 0.000025
[Epoch 36] Validation accuracy:0.7021. Loss:1.333
Model saved.
best_acc:0.7021
```

**Comment by JiaweiShiCV** [comment]
> 知道，我自己在fer2013上训练了。val acc能到70%，但是我上面这个测试代码出来的结果依然不太对。
> 
> ```shell
> batch_size: 256
> Loading pretrained weights... ../model/checkpoints/epoch27_acc0.9078.pth
> Loaded params num: 3
> Total params num: 3
> Train set size: 28709
> Validation set size: 3589
> Adam (
> Parameter Group 0
>     amsgrad: False
>     betas: (0.9, 0.999)
>     eps: 1e-08
>     lr: 0.001
>     weight_decay: 0.0001
> )
> [Epoch 1] Training accuracy: 0.4450. Loss: 1.483 LR: 0.001000
> [Epoch 1] Validation accuracy:0.4511. Loss:1.681
> best_acc:0.4511
> [Epoch 2] Training accuracy: 0.5796. Loss: 1.110 LR: 0.000900
> [Epoch 2] Validation accuracy:0.2953. Loss:2.391
> [Epoch 3] Training accuracy: 0.6148. Loss: 1.028 LR: 0.000810
> [Epoch 3] Validation accuracy:0.5754. Loss:1.173
> best_acc:0.5754
> [Epoch 4] Training accuracy: 0.6374. Loss: 0.969 LR: 0.000729
> [Epoch 4] Validation accuracy:0.5985. Loss:1.131
> best_acc:0.5985
> [Epoch 5] Training accuracy: 0.6540. Loss: 0.920 LR: 0.000656
> [Epoch 5] Validation accuracy:0.6294. Loss:0.980
> Model saved.
> best_acc:0.6294
> [Epoch 6] Training accuracy: 0.6713. Loss: 0.875 LR: 0.000590
> [Epoch 6] Validation accuracy:0.6110. Loss:0.995
> [Epoch 7] Training accuracy: 0.6880. Loss: 0.837 LR: 0.000531
> [Epoch 7] Validation accuracy:0.6325. Loss:0.938
> Model saved.
> best_acc:0.6325
> [Epoch 8] Training accuracy: 0.7040. Loss: 0.793 LR: 0.000478
> [Epoch 8] Validation accuracy:0.6239. Loss:1.083
> [Epoch 9] Training accuracy: 0.7215. Loss: 0.752 LR: 0.000430
> [Epoch 9] Validation accuracy:0.6645. Loss:0.901
> Model saved.
> best_acc:0.6645
> [Epoch 10] Training accuracy: 0.7321. Loss: 0.719 LR: 0.000387
> [Epoch 10] Validation accuracy:0.6539. Loss:0.922
> [Epoch 11] Training accuracy: 0.7548. Loss: 0.666 LR: 0.000349
> [Epoch 11] Validation accuracy:0.6275. Loss:1.001
> [Epoch 12] Training accuracy: 0.7681. Loss: 0.631 LR: 0.000314
> [Epoch 12] Validation accuracy:0.6464. Loss:0.999
> [Epoch 13] Training accuracy: 0.7863. Loss: 0.585 LR: 0.000282
> [Epoch 13] Validation accuracy:0.6701. Loss:0.910
> Model saved.
> best_acc:0.6701
> [Epoch 14] Training accuracy: 0.8053. Loss: 0.535 LR: 0.000254
> [Epoch 14] Validation accuracy:0.6807. Loss:0.936
> Model saved.
> best_acc:0.6807
> [Epoch 15] Training accuracy: 0.8251. Loss: 0.489 LR: 0.000229
> [Epoch 15] Validation accuracy:0.6740. Loss:0.924
> [Epoch 16] Training accuracy: 0.8445. Loss: 0.437 LR: 0.000206
> [Epoch 16] Validation accuracy:0.6885. Loss:0.955
> Model saved.
> best_acc:0.6885
> [Epoch 17] Training accuracy: 0.8605. Loss: 0.396 LR: 0.000185
> [Epoch 17] Validation accuracy:0.6787. Loss:0.987
> [Epoch 18] Training accuracy: 0.8782. Loss: 0.351 LR: 0.000167
> [Epoch 18] Validation accuracy:0.6893. Loss:1.045
> Model saved.
> best_acc:0.6893
> [Epoch 19] Training accuracy: 0.8879. Loss: 0.321 LR: 0.000150
> [Epoch 19] Validation accuracy:0.6821. Loss:1.018
> [Epoch 20] Training accuracy: 0.9050. Loss: 0.276 LR: 0.000135
> [Epoch 20] Validation accuracy:0.6874. Loss:1.206
> [Epoch 21] Training accuracy: 0.9202. Loss: 0.240 LR: 0.000122
> [Epoch 21] Validation accuracy:0.6893. Loss:1.085
> [Epoch 22] Training accuracy: 0.9295. Loss: 0.213 LR: 0.000109
> [Epoch 22] Validation accuracy:0.6832. Loss:1.167
> [Epoch 23] Training accuracy: 0.9364. Loss: 0.195 LR: 0.000098
> [Epoch 23] Validation accuracy:0.6927. Loss:1.188
> Model saved.
> best_acc:0.6927
> [Epoch 24] Training accuracy: 0.9479. Loss: 0.163 LR: 0.000089
> [Epoch 24] Validation accuracy:0.6927. Loss:1.160
> [Epoch 25] Training accuracy: 0.9519. Loss: 0.150 LR: 0.000080
> [Epoch 25] Validation accuracy:0.6988. Loss:1.166
> Model saved.
> best_acc:0.6988
> [Epoch 26] Training accuracy: 0.9600. Loss: 0.131 LR: 0.000072
> [Epoch 26] Validation accuracy:0.6921. Loss:1.183
> [Epoch 27] Training accuracy: 0.9634. Loss: 0.117 LR: 0.000065
> [Epoch 27] Validation accuracy:0.6899. Loss:1.221
> [Epoch 28] Training accuracy: 0.9669. Loss: 0.105 LR: 0.000058
> [Epoch 28] Validation accuracy:0.6913. Loss:1.255
> [Epoch 29] Training accuracy: 0.9712. Loss: 0.091 LR: 0.000052
> [Epoch 29] Validation accuracy:0.6952. Loss:1.241
> [Epoch 30] Training accuracy: 0.9744. Loss: 0.087 LR: 0.000047
> [Epoch 30] Validation accuracy:0.6902. Loss:1.278
> [Epoch 31] Training accuracy: 0.9767. Loss: 0.081 LR: 0.000042
> [Epoch 31] Validation accuracy:0.6949. Loss:1.271
> [Epoch 32] Training accuracy: 0.9796. Loss: 0.073 LR: 0.000038
> [Epoch 32] Validation accuracy:0.6971. Loss:1.297
> [Epoch 33] Training accuracy: 0.9806. Loss: 0.069 LR: 0.000034
> [Epoch 33] Validation accuracy:0.6963. Loss:1.283
> [Epoch 34] Training accuracy: 0.9816. Loss: 0.064 LR: 0.000031
> [Epoch 34] Validation accuracy:0.6943. Loss:1.296
> [Epoch 35] Training accuracy: 0.9828. Loss: 0.060 LR: 0.000028
> [Epoch 35] Validation accuracy:0.7016. Loss:1.306
> Model saved.
> best_acc:0.7016
> [Epoch 36] Training accuracy: 0.9849. Loss: 0.054 LR: 0.000025
> [Epoch 36] Validation accuracy:0.7021. Loss:1.333
> Model saved.
> best_acc:0.7021
> ```

应该是单张图片缺少share affinity，这个需要一个mini-batch的数据。

**Comment by hewumars** [comment]
测试是ok的， 略微下降，之前是预处理代码有些问题。
[batch_size 1] Validation accuracy:0.7002.
[batch_size 256] Validation accuracy:0.7063.

**Comment by JohnnyHopp** [comment]
> 测试是ok的， 略微下降，之前是预处理代码有些问题。
> [batch_size 1] Validation accuracy:0.7002.
> [batch_size 256] Validation accuracy:0.7063.

**Comment by JohnnyHopp** [comment]
> 测试是ok的， 略微下降，之前是预处理代码有些问题。
> [batch_size 1] Validation accuracy:0.7002.
> [batch_size 256] Validation accuracy:0.7063.

@hewumars 我自己用batch size = 64训练出来的模型accuracy正常，但是换成batch size=1做testing就会低10多个点，请问知道是什么原因吗？你这边batch size=1测试基本没影响吗？
