### ISSUE TITLE
affectnet训练代码

### ISSUE THREAD

**Issue by Yiqin-Luo** [JiaweiShiCV/Amend-Representation-Module#20]
您好！复现代码的时候，raf-db和您的结果差不多，但是affectnet的结果准确率只有60%左右，可以分享一下affectnet的训练代码么？非常感谢！

**Comment by Yiqin-Luo** [comment]
感谢

**Comment by Yiqin-Luo** [comment]
您好！我想对实验结果进行分析，可以分享一个affectnet训练好的模型么？非常感谢！

**Comment by smwanghhh** [comment]
> 您好！复现代码的时候，raf-db和您的结果差不多，但是affectnet的结果准确率只有60%左右，可以分享一下affectnet的训练代码么？非常感谢！

您好！请问您复现的时候，测试集shuffle了吗？我在复现raf-db数据集时，测试集shuffle仅86+， 加上预训练也就87+。去掉SA模块和使用整个测试集的平均特征代替batch平均特征，performance 似乎没有多大变化。
