### ISSUE TITLE
Can't load pretraiend weights direcly to ResNet18_ARM___RAF

### ISSUE THREAD

**Issue by JohnnyHopp** [JiaweiShiCV/Amend-Representation-Module#3]
Hi, Jiawei @JiaweiShiCV . Good job.
I downloaded your pretrained weights of network on RAF-DB from Google drive. But it seems that the keys in model_state_dict don't match with class ResNet18_ARM___RAF.

In the pretraiend weights, there exists `'element_attention_x.elm.weight', 'element_attention_x.bn.weight', 'element_attention_x.bn.bias', 'element_attention_x.bn.running_mean', 'element_attention_x.bn.running_var', 'element_attention_x.bn.num_batches_tracked'`, but not exist in class ResNet18_ARM___RAF.

Could you kindly explain to me how to test the model with your pretrained weights? Thanks a lot!

**Comment by JiaweiShiCV** [comment]
Sorry, before uploading the code, I changed the Module name. Please do not use the uploaded checkpoint, sorry for the trouble.

**Comment by JohnnyHopp** [comment]
> Sorry, before uploading the code, I changed the Module name. Please do not use the uploaded checkpoint, sorry for the trouble.

I see. I am wondering if you could upload the up-to-date checkpoint for us to test? Many thanks!

**Comment by JiaweiShiCV** [comment]
> > Sorry, before uploading the code, I changed the Module name. Please do not use the uploaded checkpoint, sorry for the trouble.
> 
> I see. I am wondering if you could upload the up-to-date checkpoint for us to test? Many thanks!

Checkpoint updated.
