### ISSUE TITLE
Question about using mean features in test phase

### ISSUE THREAD

**Issue by huyen-tt** [JiaweiShiCV/Amend-Representation-Module#5]
Hi @JiaweiShiCV . Great job!
I don't understand why you have to add the mean features in test phase. When I want to testing facial expression classification in only 1 image or in video stream, how can I get mean feature of batch of presentations? Thanks a lot.

**Comment by hewumars** [comment]
same question: When I want to testing facial expression classification in only 1 image or in video stream, how can I get mean feature of batch of presentations?

**Comment by JiaweiShiCV** [comment]
> Hi @JiaweiShiCV . Great job!
> I don't understand why you have to add the mean features in test phase. When I want to testing facial expression classification in only 1 image or in video stream, how can I get mean feature of batch of presentations? Thanks a lot.
#1
