### ISSUE TITLE
about de-albino

### ISSUE THREAD

**Issue by hewumars** [JiaweiShiCV/Amend-Representation-Module#6]
想请问下，no padding， kernel size 32*32 and stride 8能否换成多个4或8 kernel size的depthwise conv(in=2,out=2,group=2)，替换掉slice和concat这些操作。
主要是因为硬件不支持大于7的kernel size。

**Comment by JiaweiShiCV** [comment]
> 想请问下，no padding， kernel size 32*32 and stride 8能否换成多个4或8 kernel size的depthwise conv(in=2,out=2,group=2)，替换掉slice和concat这些操作。
> 主要是因为硬件不支持大于7的kernel size。

不建议这么做。
1.关于卷积核大小：大卷积核和步长目的是为了降低边缘albino pixels的权重，卷积核大小决定权重稀释的程度，这一点在论文中有阐述。
2.关于卷积核个数：原本是单通道卷积核对所有通道进行卷积，depthwise conv，增加了卷积核个数会导致参数量增加。这对于小数据集的训练会有过拟合倾向。
