### ISSUE TITLE
Question about the trained model

### ISSUE THREAD

**Issue by shv07** [JiaweiShiCV/Amend-Representation-Module#7]
Hi @JiaweiShiCV,

Thanks for open sourcing the wonderful work!

I had been testing the trained model you have supplied, with a small set of sample images and the outputs were not quite satisfactory (incorrect emotions and very low probabilities).  I have checked the face detection results and they are fine. Below is the code in gist I have been using. Would be grateful if you could comment on whether am I missing something or if the model supplied in drive is the latest one.

```python
torch.manual_seed(0)
np.random.seed(0)

RAF_DB_EMO_DICT = { 0:"Surprise", 1:"Fear", 2:"Disgust", 3:"Happiness", 4:"Sadness", 5:"Anger", 6:"Neutral" }
data_transforms_val = transforms.Compose([
                transforms.ToPILImage(),
                transforms.Resize((224, 224)),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
                ])

img = cv2.imread(filepath)

frame_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Detect first face in image
start_x, start_y, end_x, end_y = detect_face(frame_rgb) 

# covnert to square images
center_x, center_y = (start_x + end_x) // 2, (start_y + end_y) // 2
square_length = ((end_x - start_x) + (end_y - start_y)) // 2 // 2

square_length *= 1.1

start_x = max(int(center_x - square_length), 0)
start_y = max(int(center_y - square_length), 0)
end_x = min(int(center_x + square_length), w - 1)
end_y = min(int(center_y + square_length), h - 1)

face = frame_rgb[start_y:end_y, start_x:end_x]

img_tensor = data_transforms_val(face)
img_tensor.unsqueeze_(0)

scores = model(img_tensor.to('cuda'))
scores=torch.softmax(scores[0],dim=1)

emo_proba, emo_idx = torch.max(scores, dim=1)
emo_idx = emo_idx.item()
emo_proba = emo_proba.item()

emo_label = RAF_DB_EMO_DICT[emo_idx]
```

**Comment by JiaweiShiCV** [comment]
The model trained in RAF-DB is already the latest one. Did you directly apply it to real-time detection? I think it doesn't work because of the difference of the scene.

**Comment by shv07** [comment]
> The model trained in RAF-DB is already the latest one. Did you directly apply it to real-time detection? I think it doesn't work because of the difference of the scene.

No, I tried for some static images. Moreover the prediction results are varying when I vary the random seeds. If I don't set the random seeds at all, then the predictions change everytime I load the model (on same images).

This is how I am loading the model:-

```python
    def LoadModel(self, path:str) -> None:
        if self.model is not None:
            del(self.model)
    
        # Initialise the model object
        self.model = ResNet18_ARM___RAF()

        # Load Weights
        pretrained_state_dict = torch.load("models/epoch37_acc0.9058.pth")#, map_location=lambda storage, loc: storage)
        model_state_dict = self.model.state_dict()
        loaded_keys = 0
        total_keys = 0
        for key in pretrained_state_dict:
            if  ((key=='fc.weight')|(key=='fc.bias')):
                pass
            else:    
                model_state_dict[key] = pretrained_state_dict[key]
                total_keys+=1
                if key in model_state_dict:
                    loaded_keys+=1
        print("Loaded params num:", loaded_keys)
        print("Total params num:", total_keys)
        self.model.load_state_dict(model_state_dict, strict = False)

        # Set to evaluation mode
        self.model.to(self.device)
        self.model.eval()

 ```

**Comment by JiaweiShiCV** [comment]
> > The model trained in RAF-DB is already the latest one. Did you directly apply it to real-time detection? I think it doesn't work because of the difference of the scene.
> 
> No, I tried for some static images. Moreover the prediction results are varying when I vary the random seeds. If I don't set the random seeds at all, then the predictions change everytime I load the model (on same images).
> 
> This is how I am loading the model:-
> 
> ```python
>     def LoadModel(self, path:str) -> None:
>         if self.model is not None:
>             del(self.model)
>     
>         # Initialise the model object
>         self.model = ResNet18_ARM___RAF()
> 
>         # Load Weights
>         pretrained_state_dict = torch.load("models/epoch37_acc0.9058.pth")#, map_location=lambda storage, loc: storage)
>         model_state_dict = self.model.state_dict()
>         loaded_keys = 0
>         total_keys = 0
>         for key in pretrained_state_dict:
>             if  ((key=='fc.weight')|(key=='fc.bias')):
>                 pass
>             else:    
>                 model_state_dict[key] = pretrained_state_dict[key]
>                 total_keys+=1
>                 if key in model_state_dict:
>                     loaded_keys+=1
>         print("Loaded params num:", loaded_keys)
>         print("Total params num:", total_keys)
>         self.model.load_state_dict(model_state_dict, strict = False)
> 
>         # Set to evaluation mode
>         self.model.to(self.device)
>         self.model.eval()
> ```
Sorry. There is indeed some problem with the code, I just fixed it.

29a248dbb801fa308bdc48613ca9ae2a06977b15

**Comment by shv07** [comment]
> > > The model trained in RAF-DB is already the latest one. Did you directly apply it to real-time detection? I think it doesn't work because of the difference of the scene.
> > 
> > 
> > No, I tried for some static images. Moreover the prediction results are varying when I vary the random seeds. If I don't set the random seeds at all, then the predictions change everytime I load the model (on same images).
> > This is how I am loading the model:-
> > ```python
> >     def LoadModel(self, path:str) -> None:
> >         if self.model is not None:
> >             del(self.model)
> >     
> >         # Initialise the model object
> >         self.model = ResNet18_ARM___RAF()
> > 
> >         # Load Weights
> >         pretrained_state_dict = torch.load("models/epoch37_acc0.9058.pth")#, map_location=lambda storage, loc: storage)
> >         model_state_dict = self.model.state_dict()
> >         loaded_keys = 0
> >         total_keys = 0
> >         for key in pretrained_state_dict:
> >             if  ((key=='fc.weight')|(key=='fc.bias')):
> >                 pass
> >             else:    
> >                 model_state_dict[key] = pretrained_state_dict[key]
> >                 total_keys+=1
> >                 if key in model_state_dict:
> >                     loaded_keys+=1
> >         print("Loaded params num:", loaded_keys)
> >         print("Total params num:", total_keys)
> >         self.model.load_state_dict(model_state_dict, strict = False)
> > 
> >         # Set to evaluation mode
> >         self.model.to(self.device)
> >         self.model.eval()
> > ```
> 
> Sorry. There is indeed some problem with the code, I just fixed it.
> 
> [29a248d](https://github.com/JiaweiShiCV/Amend-Representation-Module/commit/29a248dbb801fa308bdc48613ca9ae2a06977b15)

Thanks a lot! I was able to fix the issue with a minor change to your latest commit. :-

```python
# model.load_state_dict(model_state_dict, strict = False)
model.load_state_dict(model_state_dict["model_state_dict"])
```

**Comment by JiaweiShiCV** [comment]
> > > > The model trained in RAF-DB is already the latest one. Did you directly apply it to real-time detection? I think it doesn't work because of the difference of the scene.
> > > 
> > > 
> > > No, I tried for some static images. Moreover the prediction results are varying when I vary the random seeds. If I don't set the random seeds at all, then the predictions change everytime I load the model (on same images).
> > > This is how I am loading the model:-
> > > ```python
> > >     def LoadModel(self, path:str) -> None:
> > >         if self.model is not None:
> > >             del(self.model)
> > >     
> > >         # Initialise the model object
> > >         self.model = ResNet18_ARM___RAF()
> > > 
> > >         # Load Weights
> > >         pretrained_state_dict = torch.load("models/epoch37_acc0.9058.pth")#, map_location=lambda storage, loc: storage)
> > >         model_state_dict = self.model.state_dict()
> > >         loaded_keys = 0
> > >         total_keys = 0
> > >         for key in pretrained_state_dict:
> > >             if  ((key=='fc.weight')|(key=='fc.bias')):
> > >                 pass
> > >             else:    
> > >                 model_state_dict[key] = pretrained_state_dict[key]
> > >                 total_keys+=1
> > >                 if key in model_state_dict:
> > >                     loaded_keys+=1
> > >         print("Loaded params num:", loaded_keys)
> > >         print("Total params num:", total_keys)
> > >         self.model.load_state_dict(model_state_dict, strict = False)
> > > 
> > >         # Set to evaluation mode
> > >         self.model.to(self.device)
> > >         self.model.eval()
> > > ```
> > 
> > 
> > Sorry. There is indeed some problem with the code, I just fixed it.
> > [29a248d](https://github.com/JiaweiShiCV/Amend-Representation-Module/commit/29a248dbb801fa308bdc48613ca9ae2a06977b15)
> 
> Thanks a lot! I was able to fix the issue with a minor change to your latest commit. Now the predictions don't seem to be sensitive to random seeds and are fairly better :) This is the change I did :-
> 
> ```python
> # model.load_state_dict(model_state_dict, strict = False)
> model.load_state_dict(model_state_dict["model_state_dict"])
> ```

Yes, you did it in a easier way.
