### ISSUE TITLE
 about the calculation of confusion matrixes

### ISSUE THREAD

**Issue by AMG024** [JiaweiShiCV/Amend-Representation-Module#8]
Hi @JiaweiShiCV , Great job!
can you tell me how to calculate confusion matrixes, like dataset RAF-DB, whether you calculate the each category use the Weighted Accuracy 90.58 model? Thanks a lot.

**Comment by JiaweiShiCV** [comment]
I just updated the code and pretrained model.
Please download the latest pretrained model and then try to plot Confusion Matrix by running: 

```
 python src/test_raf-db.py --checkpoint models/RAF-DB/epoch59_acc0.9205.pth --plot_cm
```

**Comment by AMG024** [comment]
@JiaweiShiCV , get it! Thank you, but why are you improve the acc on raf-db so much? Especially on the expression of fear.

**Comment by JiaweiShiCV** [comment]
The batch size has been adjusted from 256 to 64.
