### ISSUE TITLE
用batch size = 64训练出来的模型accuracy正常，但是换成batch size=1做testing就会低10多个点

### ISSUE THREAD

**Issue by JohnnyHopp** [JiaweiShiCV/Amend-Representation-Module#9]
> 测试是ok的， 略微下降，之前是预处理代码有些问题。
> [batch_size 1] Validation accuracy:0.7002.
> [batch_size 256] Validation accuracy:0.7063.

@hewumars 我自己用batch size = 64训练出来的模型accuracy正常，但是换成batch size=1做testing就会低10多个点，请问知道是什么原因吗？你这边batch size=1测试基本没影响吗？

_Originally posted by @JohnnyHopp in https://github.com/JiaweiShiCV/Amend-Representation-Module/issues/2#issuecomment-865628242_

**Comment by JiaweiShiCV** [comment]
训练时，我们需要整个batch的平均特征，所以模型的测试精度与batch size是相关的 (预训练模型的test batch size 是256)。

**Comment by JohnnyHopp** [comment]
> 训练时，我们需要整个batch的平均特征，所以模型的测试精度与batch size是相关的 (预训练模型的test batch size 是256)。

谢谢回复，我看论文跟代码也是这个意思。但是如果实际部署使用的话每次input只有一张图片无法利用batch信息，那这个发放就比较受限制呢。。。

**Comment by JiaweiShiCV** [comment]
啊，这么说的话是的，我只考虑了整体测试的精度。可以尝试训练时记录一个平均特征（bc=256），然后测试单一图片时加上，也许可以达到同样的效果。

**Comment by JohnnyHopp** [comment]
好的，谢谢！可能感觉跟batch norm的使用类似，我想想看怎么操作。
